use_frameworks!

target 'TinyPlayer_Example' do
  pod 'TinyPlayer', :path => '../'

  target 'TinyPlayer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
