use_frameworks!

target 'TinyPlayerDemo' do
    
  pod 'TinyPlayer', :path => '../'

  target 'TinyPlayerDemo_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
  
end
